const { SlashCommandBuilder, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, ComponentType, StringSelectMenuBuilder, StringSelectMenuOptionBuilder } = require('discord.js');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('help')
        .setDescription('Shows a list of available commands and their info.'),
    async execute(interaction) {
        let commandsSting = '';
        interaction.client.commands.forEach((command) => {
            if (command.data.options.length > 0) {
                let options = '';
                command.data.options.forEach((option) => {
                    if (option.required) {
                        options += ` <${option.name}>`;
                    } else {
                        options += ` [${option.name}]`;
                    }
                });

                commandsSting += `\n\n**\`/${command.data.name}\`** <:sleeping_line:1007316800956014622>${options} <:curve2:1007316798837891183>\n<:curve1:1007316796451336333> *${command.data.description}*`;
            } else {
                commandsSting += `\n\n**\`/${command.data.name}\`** <:curve2:1007316798837891183>\n<:curve1:1007316796451336333> *${command.data.description}*`;
            }
        });
        commandsSting = commandsSting.replace('undefined', '');

        let embed = new EmbedBuilder()
            .setTitle(`${interaction.client.user.username} - Help Menu`)
            .setDescription(`Hi there[!](https://www.youtube.com/watch?v=xvFZjo5PgG0)\nEver watched a Beluga video on YouTube and wished to make one yourself, but it was too difficult?\n\nI'm <@${interaction.client.user.id}> and I'm here to let you create your very own Beluga-like Discord-conversational videos in a matter of seconds! Just give me a chat script file and watch the magic.\n\n\`<>\` <:sleeping_line:1007316800956014622> required\n\`[]\` <:sleeping_line:1007316800956014622> optional${commandsSting}\n`)
            .setThumbnail(interaction.client.user.displayAvatarURL())
            .setColor(interaction.client.embedColor())
            .setFooter({ text: interaction.user.username, iconURL: interaction.user.displayAvatarURL() })
            .setTimestamp();

        const buttons = {
            example: new ButtonBuilder()
            .setCustomId('example')
            .setLabel('Example')
            .setStyle(ButtonStyle.Secondary),

            instructions: new ButtonBuilder()
            .setCustomId('instructions')
            .setLabel('Instructions')
            .setStyle(ButtonStyle.Secondary)
        }

        let row = new ActionRowBuilder()
            .addComponents(buttons.example, buttons.instructions);
        
        const response = await interaction.reply({
            embeds: [embed],
            components: [row],
            withResponse: true
        });

        const collectorFilter = (i) => i.user.id === interaction.user.id;
        try {
            const confirmation = await response.resource.message.awaitMessageComponent({ 
                filter: collectorFilter, 
                time: 60_000, 
                componentType: ComponentType.Button 
            });

            if (confirmation.customId === 'example') {
                const exampleEmbed = new EmbedBuilder()
                    .setDescription('-# Cringe script generated by ChatGPT...')
                    .setColor(interaction.client.embedColor())
                await confirmation.update({
                    files: [
                        'src/t2b/assets/example/example_script.txt',
                        'src/t2b/assets/example/example_video.mp4'
                    ],
                    embeds: [exampleEmbed],
                    components: []
                });
            } else if (confirmation.customId === 'instructions') {
                const instructionsEmbed = new EmbedBuilder()
                    .setColor(interaction.client.embedColor())
                    .setDescription("**__Script Format__**\nCreate a text file (`.txt`) with a format as given below.\nA sample chat script file (example_script.txt) is provided in the example menu of the help command.\n```WELCOME Character$^Duration#!SoundEffect\n\nCharacter:\nMessage Text$^Duration#!SoundEffect\nAnother Message$^Duration```\n**__Syntax Rules__**\n1. _Comments_: Lines starting with # are ignored\n\n2. _Join Messages_:\n    - `WELCOME Character$^Duration#!SoundEffect`\n    - Creates \"User joined\" image\n\n3. _Character Messages_:\n    - Start with `Character:`\n    - Subsequent lines are messages of the format: `Message$^Duration[#!sound]`\n\n4. _Formatting_:\n    - Bold: `**text**`\n    - Italics: `__text__`\n    - Combined: `__**text**__`\n    - Mention: `@Character`\n    - Emojis: Emojis are supported in messages 😝\n    - Durations: `$^` followed by duration in seconds (must be present at end of each message line, before sound effect, **mandatory**)\n    - Sound Effects: `#!` followed by exact name (must be present at end of each message line, **optional**)\n\n5. _Sound Effects_: Check available sound effects in the `SFX` through the </sfx:1454761206945419367> command.")
                    .setFooter({ text: interaction.user.username, iconURL: interaction.user.displayAvatarURL() })
                    .setTimestamp();
                await confirmation.update({ 
                    embeds: [instructionsEmbed],
                    components: []
                });
            }
        } catch {
            // await interaction.editReply({ content: 'Confirmation not received within 1 minute, cancelling', components: [] });
        }
    }
}